tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMOT: on-partial
    init: |
      pwd
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  - name: Initiate Frontend & Backend
    init: |
      cd /workspace/aws-bootcamp-cruddur-2023/backend-flask
      pip3 install -r requirements.txt
      cd /workspace/aws-bootcamp-cruddur-2023/frontend-react-js
      npm install
vscode:
  extensions:
    - 42Crunch.vscode-openapi
