FROM python:3.10-slim-buster
WORKDIR /backend-flask
COPY . .
RUN pip3 install -r requirements.txt
COPY start-backend /usr/local/bin
RUN chmod 770 /usr/local/bin/*
ENV FLASK_ENV=development
EXPOSE ${PORT}
CMD ["start-backend"]