version: "3.8"
services:
  cruddur-backend-flask:
    environment:
      FRONTEND_URL: "*"
      BACKEND_URL: "*"
    image: moqassem/cruddur-backend:normal
    ports:
      - "4567:4567"
  cruddur-frontend-reactjs:
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:4567"
    image: moqassem/cruddur-frontend:normal
    ports:
      - "3000:3000"
    volumes:
      - /frontend-react-js/node_modules
  dynamodb-local:
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  postgres-db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "postgres-db:/var/lib/postgresql/data"
volumes:
  postgres-db:
    driver: local
networks:
  internal-network:
    driver: bridge
    name: cruddur
